version: "3.9"
services:
  sql-server-database:
    container_name: sql-server-database
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: testja0*
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
