name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./WebApplication1

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Login into Azure Container Registry
      uses: docker/login-action@v1.10.0
      with:
        # Server address of Docker registry. If not set then will default to Docker Hub
        registry: ${{ secrets.REGISTRY_SERVERNAME }}.azurecr.io
        # Username used to log against the Docker registry
        username: ${{ secrets.REGISTRY_USERNAME }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: Build docker image
      run: |
        docker build -f WebApplication1/Dockerfile -t ${{ secrets.REGISTRY_SERVERNAME }}.azurecr.io/webapplication1:${{ github.sha }} .
        docker push ${{ secrets.REGISTRY_SERVERNAME }}.azurecr.io/webapplication1:${{ github.sha }} 
    - name: Login into Azure WebApp
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Deploy docker image to WebApp
      uses: Azure/webapps-deploy@v2
      with:
        app-name: 'ibisticfirstdockerexample'
        images: '${{ secrets.REGISTRY_SERVERNAME }}.azurecr.io/webapplication1:${{ github.sha }}'
    - name: Azure logout
      run: az logout

